<a href="https://colab.research.google.com/github/koogk7/ML_perfect_guide/blob/master/Data_Preporcessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 데이터 전처리
- 사이킷런의 머신러닝 알고리즘은 문자열 값을 입력 값으로 허용하지 않는다. 따라서 모든 문자열은 인코딩돼서 숫자 형으로 변환해야 한다. 
- 주민번호나 아이디와 같은 식별자 피처는 단순이 식별 용도로 사용되기 때문에 인코딩하지 않고 삭제하는 편이 좋음
  
## 레이블 인코딩
  - 카테고리피처를 숫자 값으로 변환하는 것
  - 레이블 인코딩은 ***선형회귀와 같은 ML알고리즘에는 적용하지 않아야한다***. 이유는 숫자 값의 경우 크도 작음에 대한 특성이 있기때문에 이에따라 가중치가 달라 질 수 있다. 트리계열의 ML 알고리즘은 숫자의 이러한 특성을 반영하지 않으므로 상관없다.

In [3]:
from sklearn.preprocessing import LabelEncoder

items = ['TV', '냉장고', '전자레인지', '믹서', '믹서']

# 객체를 생성한 후 ,fit() 과 transform()으로 레이블 인코드 수행
encoder = LabelEncoder()
encoder.fit(items) 
labels = encoder.transform(items)
print("인코딩 변환값: ", labels)
print("인코딩 클래스: ", encoder.classes_) # 0번부터 순서대로 인코딩 값 원본을 가지고 있다.
print("디코딩 원본값: ", encoder.inverse_transform([1,2,3,0,0]))

인코딩 변환값:  [0 1 3 2 2]
인코딩 클래스:  ['TV' '냉장고' '믹서' '전자레인지']
디코딩 원본값:  ['냉장고' '믹서' '전자레인지' 'TV' 'TV']


-----
## 원-핫 인코딩
  - 피처 값의 유형에 따라 새로운 피처를 추가해 고유 값에 해당하는 칼럼에만 1을 표시하고 나머지 칼럼에는 0을 표시하는 방식, 즉 여러개의 속성 중 단 한개의 속성만 1로 표시한다.
  - 로우 형태로 되있는 피처의 고유값을 컬럼 형태로 차원을 변환한 뒤, 고유 값에 해당하는 칼럼에만 1을 표시하고 나머지에는 0을 표시한다.
  - 모든 문자열 값이 숫자형 값으로 변환되야하며, 입력값으로 2차원 데이터가 필요하다
  - 판다스에서는 ***get_dummies()***를 이용해 숫가 형으로 변환 할 필요없이 바로 인코딩을 할 수 있다.

In [6]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

encoder = LabelEncoder()
encoder.fit(items) 
labels = encoder.transform(items)

# 2차원 데이터로 변환
labels = labels.reshape(-1, 1)
print(labels)

# 원-핫 인코딩을 적용
oh_encoder = OneHotEncoder()
oh_encoder.fit(labels)
oh_labels = oh_encoder.transform(labels)
print('원-핫 인코딩 데이터')
print(oh_labels.toarray())
print('원-핫 인코딩 데이터 차원')
print(oh_labels.shape)

import pandas as pd

df = pd.DataFrame({'item': items})
# pd.get_dummies(df)

[[0]
 [1]
 [3]
 [2]
 [2]]
원-핫 인코딩 데이터
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]]
원-핫 인코딩 데이터 차원
(5, 4)


/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)


item_TV  item_냉장고  item_믹서  item_전자레인지
0        1         0        0           0
1        0         1        0           0
2        0         0        0           1
3        0         0        1           0
4        0         0        1           0

---

## 피처스케일링과 정규화
- 서로 다른 변수의 값 범위를 일정한 수준으로 맞추는 작업을 ***피처 스케일링***이라하고, 대표적인 방법으로 표준화와 정규화가 있다.
- 표준화(Standardization)는 데이터의 피처 각각이 평균이 0이고 분산이 1인 가우시안 정규분포를 가진 값으로 변환하는 것을 의미  
    ![대체 텍스트](https://postfiles.pstatic.net/MjAxODA3MzFfNDIg/MDAxNTMzMDIwOTUwMjk0.rDioAfP5eatJ8SPoUOJFMZfUQtprCC99gvKFkWU6k3Yg.gDW93QnA2VR0XyYI8KFZD2bytVEhlEsDT-A8wHk9DS0g.PNG.angryking/2304E84656B1B53A07.png?type=w773)

- 정규화(Normalization)는 일반적으로 서로 다른 피처의 크기를 통합하기 위해 크기를 변환해주는 개념
- StandardScaler는 표준화를 쉽게 지원하기 위한 클래스, 개벌 피처를 평균이 0이고 분산인 1인 값으로 변환해준다.
- SVM, 선형 회귀, 로지틱회귀는 데이터가 가우시안 분포를 가지고 있다고 가정하고 구현되어 있기때문에 사전에 표쥰화를 적용하는 것은 성능향상에 중요한 요소가 될 수 있다.
- MinMaxScaler는 데이터 값을 0과 1사이의 범위 값으로 변환(음수 값이 있다면 -1~1값으로 변환), 데이터  분포가 가우시안 분포가 아닐 경우에 Min, Max Scale를 적용 해볼 수 있다.

In [13]:
from sklearn.datasets import load_iris
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler

import pandas as pd

iris = load_iris()
iris_df = pd.DataFrame(data=iris.data, columns=iris.feature_names)

print("feature들의 평균 값")
print(iris_df.mean())
print('\nfeature들의 분산 값')
print(iris_df.var())

print("StandardScaler".center(50, "#"))

# 객체 생성
scaler = StandardScaler()
scaler.fit(iris_df)
iris_scaled = scaler.transform(iris_df) # Numpy ndarray로 반환

iris_df_scaled = pd.DataFrame(data=iris_scaled, columns=iris.feature_names)
print('\nfeature들의 평균 값')
print(iris_df_scaled.mean())
print('\nfeature들의 분산 값')
print(iris_df_scaled.var())



feature들의 평균 값
sepal length (cm)    5.843333
sepal width (cm)     3.057333
petal length (cm)    3.758000
petal width (cm)     1.199333
dtype: float64

feature들의 분산 값
sepal length (cm)    0.685694
sepal width (cm)     0.189979
petal length (cm)    3.116278
petal width (cm)     0.581006
dtype: float64
##################StandardScaler##################

feature들의 평균 값
sepal length (cm)   -1.690315e-15
sepal width (cm)    -1.842970e-15
petal length (cm)   -1.698641e-15
petal width (cm)    -1.409243e-15
dtype: float64

feature들의 분산 값
sepal length (cm)    1.006711
sepal width (cm)     1.006711
petal length (cm)    1.006711
petal width (cm)     1.006711
dtype: float64
